### ISSUE TITLE
Audit records containing markup fields do not render correctly

### ISSUE THREAD

**Issue by benpetito** [skyvers/skyve#1]
When reviewing audit records of documents which contain markup (or other long text strings, e.g. memo) in the Admin -> Audit screen, the default audit comarison displays the markup field as two WSYWIG editors instead of a side by side text comparison.

Steps to reproduce:
1. Edit the admin->Contact.xml and add a markup field.
```xml
<markup name="notes">
  <displayName>Notes</displayName>
</markup>
```

2. Edit the admin->Contact->views->edit.xml and append the new field to the edit view after the last form field entry.
```xml
<row>
  <item>
    <default binding="notes" />
  </item>
</row>
```
3. Generate the domain and redeploy and launch your development server.
4. Edit a contact and add some changes to the new markup field and save the contact.
5. Review the audit record for the contact update
![audit markup display](https://cloud.githubusercontent.com/assets/2891855/21034100/0ac288ae-be05-11e6-9e6c-c107e1180906.PNG)

**Comment by sandsm** [comment]
Fixed in Skyve 20170330.
