### ISSUE TITLE
Is Flutter usable?

### ISSUE THREAD

**Issue by JulianBissekkou** [skyvers/skyve#105]
According to the [roadmap](https://skyve.org/roadmap) flutter support was planned in Q4 2022.
There is a flutter repository but from what I have seen in the source code this doesn't look like a finished product.

Can you give an update on the state of the flutter project?

**Comment by sandsm** [comment]
Hi Julian,

Thanks for your enquiry. The flutter project was delayed but is now underway. At this stage we’re aiming for an MVP by the end of this calendar year (2023).
This first tranche is focused on a single Dart/Flutter code base for both forward code generation and metadata interpretation.
We're hoping this will allow faster time to market with less code and technical debt.
We have just finished implementing the forward generation part through the skyve maven plugin which will be part of Skyve 8.3.0 to be released imminently.
Rudimentary integration to the Skyve service layer is done (user session management, data services) and we can generate or interpret very basic Flutter UIs.
There are currently gaps in this integration around declarative security, conversation usage and the like and a lot of the widget implementations are stubbed, but we still see value in its current form for generating out a scaffolded app connected to data.
This will never be a “push the button and get a finished native app” function though as we feel a good mobile UX will almost always require customisation to meet expectations, but more likely it will generate out ~75% of your native application, with the remaining functions to be finessed by developers.
Our aim is to try to reduce the cost and effort of creating a "mobile companion app" for your Skyve application by say 50% initially, and improve that over time.
We will be catering specifically for the web as well so it will function as a new Skyve renderer for browsers.
We’re currently aiming for a full flutter implementation for the Skyve UI in Q1-Q2 2024, however this will depend on whether our customers have other priorities.
 
Cheers,
Mike.

**Comment by JulianBissekkou** [comment]
Thanks for the update and all the insights.
I will close this issue now because my question was answered

**Comment by sandsm** [comment]
Thanks Julian.
You can jump on our skyve slack if you wanna discuss more or contribute or anything.
