### ISSUE TITLE
Update Skyve to work with Java 21

### ISSUE THREAD

**Issue by dgcooke** [skyvers/skyve#106]
Updating to Java 17 or 21 will assist in the uplift to Jakarta EE 10.  It has several benefits including better multi-threaded performance via virtual threads(21), will give us the ability to use Java Records (17) and also the GCs have been improved for most workloads (21).

**Comment by benpetito** [comment]
Hi @dgcooke , that is something we have wanted to do but haven't had a chance to yet!

**Comment by benpetito** [comment]
This has been implemented as part of [Skyve 9](https://skyve.org/blog/2024/5/4/skyve-900-released). Skyve 9 is compiled against JDK 17, but is compatible and tested with JDK 21.
