### ISSUE TITLE
Zero downtime migration

### ISSUE THREAD

**Issue by dumblob** [skyvers/skyve#94]
Newbie here. I wonder if and how Skyve supports zero downtime updates, upgrades, and downgrades?

Could you elaborate?

Thanks!

**Comment by benpetito** [comment]
Hi @dumblob,

Thanks for your question!

Zero downtime is dependent on the infrastructure Skyve is being deployed upon. Skyve applications require a compatible application server (currently Wildfly) to run. In a simple deployment, there would be a single application server, and a minimal outage when new versions are deployed (typically 1-2 mins). If zero downtime was required, multiple Wildfly application servers could be deployed behind a load balancer. This could be achieved with something like Kubernetes' blue/green deployment mechanism. Multiple concurrent Skyve instances would require a modification to the out-of-the-box [content service](https://skyvers.github.io/skyve-dev-guide/working-with-content/) to use something like Elastic Search to prevent file locking.

Skyve supports schema evolution to apply upgrades automatically and provides a [database independent backup](https://skyvers.github.io/skyve-dev-guide/backup-restore/) mechanism if a manual downgrade is required.

If you are using [Skyve Foundry](https://foundry.skyve.org/foundry), it can work with Git for source control and can version deployments via Docker images and rollback failed changes to a known good version/image.

Skyve also provides the ability to override application changes for different [customers/tenants](https://skyvers.github.io/skyve-dev-guide/customers/) within the same application. For example, if one customer is on a certain version and another customer needs changes for a new version not yet available for all customers.

Hopefully that answers your questions.

**Comment by dumblob** [comment]
Thanks, great technical answers!

Maybe one more - do you have any standing plans to improve on the requirement of the following?

>This could be achieved with something like Kubernetes' blue/green deployment mechanism. Multiple concurrent Skyve instances would require a modification to the out-of-the-box content service to use something like Elastic Search to prevent file locking.

In other words, will you offer an "off the shelf" solution which will ensure these steps are safely automatically done with no user intervention needed?

**Comment by sandsm** [comment]
Nice Ben

From: Ben Petito ***@***.***>
Date: Thursday, 16 March 2023 at 5:17 pm
To: skyvers/skyve ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [skyvers/skyve] Zero downtime migration (Issue #94)

[EXTERNAL EMAIL] DO NOT Click links or open attachments unless you recognize the sender and know the content is safe. 9993ca13-50fd-4d1d-94b8-99b16577119b

Hi @dumblob<https://github.com/dumblob>,

Thanks for your question!

Zero downtime is dependent on the infrastructure Skyve is being deployed upon. Skyve applications require a compatible application server (currently Wildfly) to run. In a simple deployment, there would be a single application server, and a minimal outage when new versions are deployed (typically 1-2 mins). If zero downtime was required, multiple Wildfly application servers could be deployed behind a load balancer. This could be achieved with something like Kubernetes' blue/green deployment mechanism. Multiple concurrent Skyve instances would require a modification to the out-of-the-box content service<https://skyvers.github.io/skyve-dev-guide/working-with-content/> to use something like Elastic Search to prevent file locking.

Skyve supports schema evolution to apply upgrades automatically and provides a database independent backup<https://skyvers.github.io/skyve-dev-guide/backup-restore/> mechanism if a manual downgrade is required.

If you are using Skyve Foundry<https://foundry.skyve.org/foundry>, it can work with Git for source control and can version deployments via Docker images and rollback failed changes to a known good version/image.

Skyve also provides the ability to override application changes for different customers/tenants<https://skyvers.github.io/skyve-dev-guide/customers/> within the same application. For example, if one customer is on a certain version and another customer needs changes for a new version not yet available for all customers.

Hopefully that answers your questions.

**Comment by sandsm** [comment]
Hi @dumblob,

We need to resurrect our elastic content implementation for other customers, but we don’t plan to implement blue/green kubernetes deployments as part of our open source offering.  That sort of thing is provided in our infrastructure/hosting solution which is part of the Foundry service. Please contact us directly if you are interested in a custom hosted solution to solve this need.

**Comment by dumblob** [comment]
>That sort of thing is provided in our infrastructure/hosting solution which is part of the Foundry service. Please contact us directly if you are interested in a custom hosted solution to solve this need.

Both options (cloud solution as well as on-premises) are under consideration.

Could you post a link to your current cloud offering and its zero-downtime-related guarantees (SLAs and other technicalities - incl. e.g. a detailed upgrade guide)? Thanks!

**Comment by benpetito** [comment]
Hi @dumblob,

the open source Skyve platform is offered as a software solution, not a hosted infrastructure solution. Can you please [contact us](https://skyve.org/contact directly if you are interested in a zero-downtime hosted software and infrastructure solution? 

[Skyve Foundry](https://foundry.skyve.org) is our hosted SaaS offering, and you can view the SLA [here](https://foundry.skyve.org/sla.html), but this is not offered as a zero-downtime.

**Comment by dumblob** [comment]
> [Skyve Foundry](https://foundry.skyve.org) is our hosted SaaS offering, and you can view the SLA [here](https://foundry.skyve.org/sla.html), but this is not offered as a zero-downtime.

Thanks!
