### ISSUE TITLE
About the workflow

### ISSUE THREAD

**Issue by leoWu93** [skyvers/skyve#98]
How to use process engine-related plug-ins in the open source version?

**Comment by benpetito** [comment]
Hi @leoWu93,

thank you for your question. I'm not sure I quite understand sorry, could you provide some more information and do you have a specific example of an integration you want to use with Skyve?

Thanks

**Comment by leoWu93** [comment]
@benpetito   I mean，Is there any workflow related content in the open source version of Skyve?

**Comment by benpetito** [comment]
Hi @leoWu93 ,

No, simple workflows can be built easily in Skyve using the available low-code and some basic business logic. We have done this many times for many different clients across a variety of business domains. We are in the process of building a workflow engine in Skyve, but we will not be able to support this under the open-source platform, it will be a paid add-on.

**Comment by leoWu93** [comment]
@benpetito  ok,Thank you for taking the time to answer my doubts
